### ISSUE TITLE
Frontend checklist

### ISSUE THREAD

**Issue by albburtsev** [albburtsev/burtsev.me#1]
# Frontend-developer's checklist
### Common stuff: pages, styles, etc
- [x] Check responsive design for typical resolutions (320, 480, 1024, 1600, 2k)
- [x] [Viewport](https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag) meta tag
- [x] X-UA-Compatible meta tag <sup>1</sup>
- [x] Format detection meta tags <sup>2</sup>
- [x] Page 404
- [x] Page 5xx
- [x] Print version
- [x] Noscript version
- [x] Proper cache for all static files
- [x] [Apple-specific](https://developer.apple.com/library/safari/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html) meta tags
- [x] All absolute pathes without protocol
### Graphics
- [x] Favicon 16x16, 32x32 <sup>3</sup>
- [x] Apple icons <sup>4</sup>
- [x] Android icons <sup>5</sup>
- [x] Support retina displays
- [x] Sprites and icon fonts
- [x] Minify all images with [Imagemin](https://github.com/gruntjs/grunt-contrib-imagemin)
- [x] Image inlining (for instance [in Stylus](http://learnboost.github.io/stylus/docs/functions.url.html))
### SEO and Social
- [x] robots.txt
- [x] humans.txt
- [ ] Mark up content with [microdata](http://schema.org/)
- [x] Social likes buttons
- [ ] Common meta tags <sup>6</sup>
- [x] [Facebook OG](https://developers.facebook.com/docs/opengraph/using-objects?locale=ru_RU#selfhosted-creating) meta tags
- [x] [Twitter cards](https://dev.twitter.com/cards/markup) meta tags
- [x] [GA](http://www.google.com/analytics/) and other statistic
- [x] [Google webmasters](http://www.google.com/webmasters/)
### Validation and performance
- [ ] [Google PageSpeed](https://developers.google.com/speed/pagespeed/) tools
- [x] [HTML validation](http://validator.w3.org/check)
- [x] [CSS validation](http://jigsaw.w3.org/css-validator/validator)
- [x] [Link checker](http://validator.w3.org/checklink)
### Build systems
- [x] Deploy task for build system
- [x] Code style (jshint, jscs) for JavaScript code
- [ ] [Autoprefixer](https://github.com/postcss/autoprefixer) for all styles
- [x] Don't save builds in project's VCS
- [x] Check project's deployment (all stuff must be in config files: package.json, bower.json)
- [ ] `npm test` required

---

<sup>[1] X-UA-Compatible</sup>

``` html
<meta http-equiv="X-UA-Compatible" content="IE=edge">
```

<sup>[2] Format detection</sup>

``` html
<meta name="format-detection" content="telephone=no"/>
<meta name="format-detection" content="address=no"/>
```

<sup>[3] Favicon</sup>

``` html
<link rel="shortcut icon" type="image/x-icon" href="path/to/icon.ico"/>
```

<sup>[4] Apple icons</sup>

``` html
<link rel="apple-touch-icon" href="57x57.png">
<link rel="apple-touch-icon" href="72x72.png" sizes="72x72">
<link rel="apple-touch-icon" href="114x114.png" sizes="114x114">
<link rel="apple-touch-startup-image" href="57x57.png">
```

<sup>[5] Android icons</sup>

``` html
<link rel="icon" sizes="192x192" href="nice-highres.png">
<link rel="icon" sizes="128x128" href="niceicon.png">
```

<sup>[6] Common meta tags</sup>

``` html
<meta name="description" content="" />
<meta name="keywords" content="" />
<meta name="author" content="" />
<meta name="copyright" content="" /> 
```
